### ISSUE TITLE
Instructions to Flash RP2040 Missing Which Board to Use

### ISSUE THREAD

**Issue by andyroy255** [YooSHome/SenseCapConfig#3]
Putting this up there in case it helps anyone else! 

Compiling the Arduino demo using the build in Arduino RP2040 Raspberry Pi Pico gives me compile errors. 

Using this guide to install a different board, allows the selection of the Seed INDICATOR RPI 2040 and resolves any compile issues from the demo Arduino sketch. Hope that helps and thanks for the cool project!

https://learn.adafruit.com/rp2040-arduino-with-the-earlephilhower-core/installing-the-earlephilhower-core

**Comment by Love4yzp** [comment]
Actually, you can find more dedicated details here for RP2040: https://wiki.seeedstudio.com/SenseCAP_Indicator_How_To_Flash_The_Default_Firmware/#for-rp2040
