### ISSUE TITLE
Black Screen with FPS and CPU load

### ISSUE THREAD

**Issue by aweinmann** [YooSHome/SenseCapConfig#4]
Hi,
I tried flashing this project to my D1S and it only shows FPS and CPU load in the right bottom corner.
This is the monitor log:
```
I (1074) i2c_bus: i2c0 bus inited
I (1078) bsp boards: detecting board SenseCAP_Indicator
I (1084) bsp boards: Detected board: [SenseCAP_Indicator]
I (1095) gpio: GPIO[38]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (1114) gpio: GPIO[45]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (1126) gpio: GPIO[41]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (1126) gpio: GPIO[48]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (1536) sx126x: bsp sx126x init
I (1536) sx126x: spi_bus_initialize=0
I (1536) sx126x: spi_bus_add_device=0
I (1540) lvgl_port: Add TP input device to LVGL
E (11557) sensor-model: The time is not right!!!
E (21557) sensor-model: The time is not right!!!
E (31557) sensor-model: The time is not right!!!
E (41557) sensor-model: The time is not right!!!
E (51557) sensor-model: The time is not right!!!
```

It continues to show: The time is not right!!

any clue what the issue is there? Thanks in advance!

**Comment by Love4yzp** [comment]
https://github.com/YooSHome/SenseCapConfig/blob/8d8cef45d43d1bad979d8d168bb5ec5687ead781/ESP32/main/model/indicator_sensor.c#L533-L538
it will show if you didn't sync the time.
 it's fine sometimes.

**Comment by aweinmann** [comment]
The original HA sample works fine for me but this stays black forever only showing fps and CPU

**Comment by Yoobe** [comment]
The black screen is probably due to the json file content/issue
During the loading of screens from json, there might be an issue and then there is no UI loaded.

Can you share your json file you store in your sd card?

**Comment by aweinmann** [comment]
The issue was related to the SD-Card, I formatted the card again and now its working. Thanks!

**Comment by Yoobe** [comment]
ok nice.
Be aware that the code is not final. 
I had to stop working on that before finishing the implement of the screens/widgets. I plan to come back to that later when I deploy home assistant in my new home...
It works well for some buttons and data display. for other sizes (medium, small) it is not finished.
